version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/work

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - .:/work
    depends_on:
      - php
    ports:
      - 80:80

  php-cli:
    build:
      context: .
      dockerfile: ./docker/php-cli/Dockerfile
    volumes:
      - .:/work

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - .:/work
